### ISSUE TITLE
I have an error

### ISSUE THREAD

**Issue by memopycsjj** [halbux/sparselizard-users#8]
Hi,
I found this error during compiling of the code:
/home/memo/compila/sparselizard/api_python/api/python/src/sl_wrapper.cpp:186:42: error: ‘predefinedacoustics’ is not a member of ‘sl’; did you mean ‘predefinedacousticwave’?
  186 |     m.def("predefinedacousticwave", &sl::predefinedacoustics, py::arg("dofp"), py::arg("tfp"), py::arg("soundspeed"), py::arg("neperattenuation"));
      |                                          ^~~~~~~~~~~~~~~~~~~
      |                                          predefinedacousticwave

And even if I set out it as suggested, other errors come up:
/home/memo/compila/sparselizard/api_python/api/python/src/sl_wrapper.cpp:79:42: error: no matching function for call to ‘pybind11::module_::def(const char [3], <unresolved overloaded function type>, pybind11::arg)’
   79 |     m.def("dt", &sl::dt, py::arg("input"));
      |                                          ^

Where I'm wrong?
Thank you

**Comment by halbux** [comment]
Thanks for the info. Fixed the predefinedacoustics. I am afraid I don't have the time to otherwise maintain much more than that the python api now :/
